import { Metadata } from 'next';
import { InterFont, OutfitFont, PoppinsFont } from './fonts';
import ProvidersWrapper from '@/src/providers';
import '@/src/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en" className={PoppinsFont.className}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', () => {
                  navigator.serviceWorker.register('/sw.js');
                });
              }
            `,
          }}
        />
        <link rel="manifest" href="/manifest.json" />
      </head>

      <body
        className={` ${OutfitFont.variable} ${PoppinsFont.variable} ${InterFont.variable} antialiased`}
      >
        <ProvidersWrapper>
          <div
            id="main-scroll-container"
            className="scrollbar-hide h-screen w-screen overflow-y-auto"
          >
            {children}
          </div>
        </ProvidersWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
