import { Suspense } from 'react';
import { Metadata } from 'next';
import { InterFont, OutfitFont, PoppinsFont } from './fonts';
import ProvidersWrapper from '@/src/providers';
import '@/src/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

<head>
  <link rel="manifest" href="/manifest.json" />
  <meta name="theme-color" content="#000000" />
  <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
</head>;

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className={PoppinsFont.className}>
      <body
        className={` ${OutfitFont.variable} ${PoppinsFont.variable} ${InterFont.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <ProvidersWrapper>
            <div
              id="main-scroll-container"
              className="scrollbar-hide h-screen w-screen overflow-y-auto"
            >
              {children}
            </div>
          </ProvidersWrapper>
        </Suspense>
      </body>
    </html>
  );
};

export default RootLayout;
