import type { Metadata } from "next";
import {  Poppins, Inter, Outfit } from "next/font/google";
import "./globals.css";

const OutfitFont = Outfit({
  variable: "--font-Outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const InterFont = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className={InterFont.className}>
      <body
        className={`
      
          ${OutfitFont.variable} 
          ${PoppinsFont.variable} 
          ${InterFont.variable} 
          antialiased`}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
